site_name: Collective Chapters
site_description: A living book of global answers to shared questions.
site_url: https://openupbooks.github.io/CollectiveChapters/
repo_url: https://github.com/yourname/CollectiveChapters
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  language: en

nav:
  - Home: index.md
  - Questions: questions/index.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - with-pdf:
      output_path: book.pdf
      cover_title: "Collective Chapters by Open Up Books"
      cover_subtitle: "A community experiment in open writing"
      author: "The Community"
      toc_level: 2
      enabled_if_env: ALWAYS_PDF

extra:
  pdf_url: book.pdf
