site_name: Collective Chapters
site_description: A global open writing project on life’s big philosophical questions.
site_url: https://example.github.io/collectivechapters/
repo_url: https://github.com/openupbooks/collectivechapters

theme:
  name: material
  language: en
  favicon: assets/favicon.png
  logo: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: grey
      accent: grey

nav:
  - Home: index.md
  - Chapters: chapters/index.md
  - About Project: pages/about.md
  - All contributors: pages/contributors.md
  - Contact: pages/contact.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list 

plugins:
  - search

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX   # Replace with your GA4 property
